### ISSUE TITLE
My suggestions after I read your excellent work

### ISSUE THREAD

**Issue by MouriNaruto** [gerhart01/Hyper-V-Internals#1]
Thank you for your excellent work. I have studied a lot after I read it and I think I should write something.

- I haven't found `computecore.dll` in your Hyper-V, WDAG and WSB components images. It has appeared since Windows 10 Version 1809. It's the dynamic library for Host Compute System APIs. It's also in the public. Here is the documentation: https://docs.microsoft.com/en-us/virtualization/api/hcs/overview
-  I haven't found `computenetwork.dll` in your Hyper-V, WDAG and WSB components images. It has appeared since Windows 10 Version 1809. It's the dynamic library for Host Compute Network APIs. It's also in the public. Here is the documentation: https://docs.microsoft.com/en-us/windows-server/networking/technologies/hcn/hcn-top
- Maybe you can provide the link for https://github.com/microsoft/hcsshim to help people to discover the undocumented Host Compute Service APIs and Host Network Service APIs in `vmcompute.dll`. It may also helpful for people to use documented Host Compute System APIs and Host Compute Network APIs because the most JSON definitions for them can be shared.
- I think `vmcompute.dll` maybe not the Windows Container specific because it will be installed if we enable any Windows feature related to Hyper-V.
- I hope my work (https://github.com/M2Team/NanaBox) can be mentioned in your Hyper-V research history list. Because I want to help more people more easier to write a third-party Hyper-V client based on Host Compute System APIs.

Kenji Mouri

**Comment by gerhart01** [comment]
Thanks, MouriNaruto. Container is not necessary run in Hyper-V environment, therefore i didn't mention it in Hyper-V related resources. Probably, i will be added it in future (but link on API will be added)
Agree, you did great work! I will add NanaBox in Hyper-V related open source utilities, scripts part

**Comment by gerhart01** [comment]
Hyper-V Researches History List was updated.
