### ISSUE TITLE
can you add these to research list

### ISSUE THREAD

**Issue by 474172261** [gerhart01/Hyper-V-Internals#2]
Hi gerhart, 

Your collection of Hyper-V research is great, but I notice that you haven't add these two slides:
https://www.blackhat.com/us-22/briefings/schedule/#directx-the-new-hyper-v-attack-surface-26442
https://github.com/howknows/hypervvulners_bhusa2021

They are all about hyper-v research, maybe you can add them to "HyperResearchesHistory".

**Comment by gerhart01** [comment]
Hello! Of course, perfect work, i will be added it in research list. 
Btw, you can ping me in twitter for this )

**Comment by gerhart01** [comment]
Hyper-V Researches History List was updated
