### ISSUE TITLE
Is QEMU working with Hyper-V?

### ISSUE THREAD

**Issue by mediaexplorer74** [gerhart01/Hyper-V-Internals#3]
Look at https://github.com/gerhart01/Hyper-V-Internals/blob/master/HyperVResearchesHistory.md

Discover

...
Software and tools, working with Hyper-V
Linux Integration Services (LIS). [Link](https://github.com/LIS)
Microsoft Linux kernel for Hyper-V root partition [Link](https://lore.kernel.org/linux-hyperv/)
MemProcFS. [Link](https://github.com/ufrisk/MemProcFS)

Qemu source code (WHPX support module).
...

There are "forks" (replicas) of Qemu for Android (world of ARM, not x86-based cpu) or (and) iOS (Apple Watch). I don't think that any kind of Hyper-V used on that device sets...

maybe, my understanding of Hyper-V technology wrong... What's Hyper-V, in short? Hardware virtualization on x86-based cpu?...

**Comment by gerhart01** [comment]
Qemu has option -accel whpx, which is supported by Hyper-V

**Comment by Zero-Tang** [comment]
For how QEMU works with Hyper-V, check the [accelerator's source code](https://github.com/qemu/qemu/tree/master/target/i386/whpx)

**Comment by mediaexplorer74** [comment]
> For how QEMU works with Hyper-V, check the [accelerator's source code](https://github.com/qemu/qemu/tree/master/target/i386/whpx)

Thank you. last year I tried to fork Qemu and port to UWP ... result is "epic fail" (i have no skills at all)
